language: node_js
cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '6'

install: true

script:
  - sh -x ./scripts/_build.sh -e

after_success:
  - npm prune
  - npm run semantic-release
  - sh -x ./scripts/_post-release.sh -e

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
